[features]
seeds = false
skip-lint = false
[programs.localnet]
got = "D8f47hT2NXBUJjU1hGERmnwA3z9zj7Jgy2WhnLm1a3zt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nejc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
