[features]
seeds = false
skip-lint = false
[programs.localnet]
day27 = "3PPpBczWaqqitCZHYWrFvGyXJevNTB21rWTfL5ncF3GK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nejc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
