[features]
seeds = false
skip-lint = false
[programs.localnet]
day28 = "8YkLsEFk5ApK9NxdtrXZCVW7tEykAT4aU857ou2U4FNw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nejc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
