[features]
seeds = false
skip-lint = false
[programs.localnet]
day25 = "7YnuL66xr2JNEwS7Tq62Pf6jxvWpg9gMM6hDLHbZBRDr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nejc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
